name: Build Tweak

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Theos
        run: |
          brew install ldid
          git clone --recursive https://github.com/theos/theos.git ~/theos
          
          # Use Git Clone for SDKs to avoid tar errors
          mkdir -p ~/theos/sdks
          git clone --depth 1 https://github.com/theos/sdks.git tmp_sdks
          mv tmp_sdks/*.sdk ~/theos/sdks/
          rm -rf tmp_sdks
          
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "~/theos/bin" >> $GITHUB_PATH

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1
        env:
          THEOS: ~/theos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NusukTweak-Package
          path: packages/*.deb
